try:
    a = 3
except Exception as e:
    print(a)
print(a)